stages:
  - build
  - deploy
  - test

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run prerender
  artifacts:
    paths:
      - dist

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY

integration_tests:
  image: cypress/browsers:node16.13.2-chrome100-ff98
  stage: test
  script: 
    - npm ci
    - npm run cy:run:prod
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
      - tests/cypress/screenshots/**/**.png
    expire_in: 1 day

