stages:
  - build
  - deploy
  - test

  image: node:latest

build:
  stage: build
  script:
    - npm install
    - npm run prerender
  artifacts:
    paths:
      - dist

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY

integration_tests:
  stage: test
  script: 
    - npm run cy:run:prod