stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build --prod
  artifacts:
    paths:
      - dist/

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
