stages:
  - build
  - deploy
  - test

image: node:latest

build:
  stage: build
  script:
    - npm install
    - npm run prerender
  artifacts:
    paths:
      - dist

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY

integration_tests:
  image: cypress-12.14.0-node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
  stage: test
  script: 
    - npm ci
    - npm start &
    - npm run cy:run:prod
