stages:
  - build
  - deploy
  - test

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run prerender
  artifacts:
    paths:
      - dist

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY

integration_tests:
  image: cypress/browsers
  stage: test
  script: 
    - npm ci
    - npm run cy:run:prod
  artifacts:
    paths:
      - /builds/Martin-Oc/test-app/tests/cypress/screenshots/end-to-end.spec.ts/**.png 

